services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cornerback
    ports:
      - "5433:5432"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
